# Generated by Django 4.2.7 on 2023-12-16 02:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_category_feedback_exercise_nutrition'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutrition',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
