# Generated by Django 4.2.7 on 2023-12-16 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_nutrition_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='name',
            new_name='имя',
        ),
    ]
