# Generated by Django 4.2.7 on 2023-12-16 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_имя_exercise_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='day',
            new_name='день',
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='category',
            new_name='категория',
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='name',
            new_name='название',
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='description',
            new_name='описание',
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='photo',
            new_name='фото',
        ),
    ]
