# Generated by Django 4.2.7 on 2023-12-16 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_day_exercise_день_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='категория',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='день',
            new_name='day',
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='описание',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='название',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='фото',
            new_name='photo',
        ),
    ]
