# Generated by Django 4.2.7 on 2023-12-16 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_nutrition_options_remove_nutrition_exercise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrition',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
    ]
